<a href="https://colab.research.google.com/github/omarEssam-11/Data-Science/blob/main/Pandas_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas**

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [4]:
pd.set_option('display.max_columns', None)
df = pd.read_csv('/content/world_population.csv')
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

## **Filtering & Ordering**

## **Filter on column**

In [5]:
df[df['Rank'] > 10]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [6]:
df[df['Continent'] == 'Africa']

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
5,42,AGO,Angola,Luanda,Africa,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
21,77,BEN,Benin,Porto-Novo,Africa,13352864.0,12643123.0,10932783.0,9445710.0,6998023.0,5133419.0,3833939.0,3023443.0,112622.0,118.5635,1.0274,0.17
26,144,BWA,Botswana,Gaborone,Africa,2630296.0,2546402.0,2305171.0,2091664.0,1726985.0,1341474.0,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
31,58,BFA,Burkina Faso,Ouagadougou,Africa,22673762.0,21522626.0,18718019.0,16116845.0,11882888.0,9131361.0,6932967.0,5611666.0,272967.0,83.0641,1.0259,0.28
32,78,BDI,Burundi,Bujumbura,Africa,12889576.0,12220227.0,10727148.0,9126605.0,6307659.0,5483793.0,4312834.0,3497834.0,27834.0,463.0874,1.0270,0.16
34,53,CMR,Cameroon,Yaounde,Africa,27914536.0,26491087.0,23012646.0,19878036.0,15091594.0,11430520.0,8519891.0,6452787.0,475442.0,58.7128,1.0263,0.35
36,171,CPV,Cape Verde,Praia,Africa,593149.0,582640.0,552166.0,521212.0,458251.0,364563.0,317234.0,287262.0,4033.0,147.0739,1.0089,0.01
38,117,CAF,Central African Republic,Bangui,Africa,5579144.0,5343020.0,4819333.0,4660067.0,3759170.0,2809221.0,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07
39,69,TCD,Chad,N'Djamena,Africa,17723315.0,16644701.0,14140274.0,11894727.0,8259137.0,5827069.0,4408230.0,3667394.0,1284000.0,13.8032,1.0316,0.22
43,163,COM,Comoros,Moroni,Africa,836774.0,806166.0,730216.0,656024.0,536758.0,431119.0,328328.0,242351.0,1862.0,449.3953,1.0184,0.01
52,160,DJI,Djibouti,Djibouti,Africa,1120849.0,1090156.0,1006259.0,919199.0,742033.0,577173.0,324121.0,144379.0,23200.0,48.3125,1.0138,0.01
55,15,COD,DR Congo,Kinshasa,Africa,99010212.0,92853164.0,78656904.0,66391257.0,48616317.0,35987541.0,26708686.0,20151733.0,2344858.0,42.2244,1.0325,1.24
57,14,EGY,Egypt,Cairo,Africa,110990103.0,107465134.0,97723799.0,87252413.0,71371371.0,57214630.0,43748556.0,34781986.0,1002450.0,110.7188,1.0158,1.39
59,152,GNQ,Equatorial Guinea,Malabo,Africa,1674908.0,1596049.0,NaN,1094524.0,684977.0,465549.0,282509.0,316955.0,28051.0,59.7094,1.0247,0.02
60,132,ERI,Eritrea,Asmara,Africa,3684032.0,3555868.0,3340006.0,3147727.0,2392880.0,2149960.0,1657982.0,1272748.0,117600.0,31.3268,1.0176,0.05
62,159,SWZ,Eswatini,Mbabane,Africa,NaN,1180655.0,1133936.0,1099920.0,1030496.0,854011.0,598564.0,442865.0,17364.0,69.2047,1.0079,0.02
63,12,ETH,Ethiopia,Addis Ababa,Africa,123379924.0,117190911.0,102471895.0,89237791.0,67031867.0,47878073.0,34945469.0,28308246.0,1104300.0,111.7268,1.0257,1.55
71,146,GAB,Gabon,Libreville,Africa,2388992.0,2292573.0,2028517.0,1711105.0,1272935.0,983028.0,749078.0,597192.0,267668.0,8.9252,1.0204,0.03
72,142,GMB,Gambia,Banjul,Africa,2705992.0,2573995.0,2253133.0,NaN,NaN,NaN,NaN,NaN,10689.0,253.1567,1.0250,0.03
75,47,GHA,Ghana,Accra,Africa,33475870.0,32180401.0,28870939.0,25574719.0,19665502.0,15446982.0,11865246.0,8861895.0,238533.0,140.3406,1.0196,0.42
84,75,GIN,Guinea,Conakry,Africa,13859341.0,13205153.0,11625998.0,10270728.0,8336967.0,6354145.0,4972609.0,4222374.0,245857.0,56.3716,1.0242,0.17
85,149,GNB,Guinea-Bissau,Bissau,Africa,2105566.0,2015828.0,1788919.0,1567220.0,1230849.0,973551.0,831462.0,591663.0,36125.0,58.2856,1.0218,0.03
100,52,CIV,Ivory Coast,Yamoussoukro,Africa,28160542.0,26811790.0,23596741.0,21120042.0,16799670.0,11910540.0,8303809.0,5477086.0,322463.0,NaN,NaN,0.35
106,27,KEN,Kenya,Nairobi,Africa,54027487.0,51985780.0,46851488.0,41517895.0,30851606.0,23162269.0,16187124.0,11473087.0,580367.0,93.0919,1.0193,0.68
113,147,LSO,Lesotho,Maseru,Africa,2305825.0,2254100.0,2118521.0,2022747.0,1998630.0,1798997.0,1407672.0,1023481.0,30355.0,75.9620,1.0107,0.03
114,121,LBR,Liberia,Monrovia,Africa,5302681.0,5087584.0,4612329.0,4019956.0,2895224.0,2209731.0,1932169.0,1463563.0,111369.0,47.6136,1.0210,0.07
115,107,LBY,Libya,Tripoli,Africa,6812341.0,6653942.0,6192235.0,6491988.0,5154790.0,4236983.0,2962720.0,1909177.0,1759540.0,3.8717,1.0114,0.09
120,50,MDG,Madagascar,Antananarivo,Africa,29611714.0,28225177.0,24850912.0,21731053.0,16216431.0,11882762.0,8948162.0,6639751.0,587041.0,50.4423,1.0241,0.37
121,62,MWI,Malawi,Lilongwe,Africa,20405317.0,19377061.0,16938942.0,14718422.0,11229387.0,9539665.0,6267369.0,4625141.0,118484.0,172.2200,1.0259,0.26
124,59,MLI,Mali,Bamako,Africa,22593590.0,21224040.0,18112907.0,15529181.0,11239101.0,8945026.0,7372581.0,6153587.0,1240192.0,18.2178,1.0314,0.28
128,126,MRT,Mauritania,Nouakchott,Africa,4736139.0,4498604.0,3946220.0,3419461.0,2695003.0,2006027.0,1506694.0,1122198.0,1030700.0,4.5951,1.0263,0.06
129,157,MUS,Mauritius,Port Louis,Africa,1299469.0,1297828.0,1293153.0,1283330.0,1215930.0,1090290.0,954865.0,830115.0,2040.0,636.9946,1.0004,0.02
130,182,MYT,Mayotte,Mamoudzou,Africa,326101.0,305587.0,249545.0,211786.0,159215.0,92659.0,52233.0,35383.0,374.0,871.9278,1.0319,0.00
138,40,MAR,Morocco,Rabat,Africa,37457971.0,36688772.0,34680458.0,32464865.0,28554415.0,24570814.0,19678444.0,15274351.0,446550.0,83.8830,1.0103,0.47
139,48,MOZ,Mozambique,Maputo,Africa,32969517.0,31178239.0,NaN,NaN,17768505.0,13303459.0,11413587.0,8411676.0,801590.0,41.1302,1.0278,0.41
141,145,NAM,Namibia,Windhoek,Africa,2567012.0,2489098.0,2282704.0,2099271.0,1819141.0,1369011.0,975994.0,754467.0,825615.0,3.1092,1.0146,0.03
148,54,NER,Niger,Niamey,Africa,26207977.0,24333639.0,20128124.0,16647543.0,11622665.0,8370647.0,6173177.0,4669708.0,1267000.0,20.6851,1.0378,0.33
149,6,NGA,Nigeria,Abuja,Africa,218541212.0,208327405.0,183995785.0,160952853.0,122851984.0,95214257.0,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
168,114,COG,Republic of the Congo,Brazzaville,Africa,5970424.0,5702174.0,5064386.0,4437884.0,3134030.0,2385435.0,1829256.0,1396989.0,342000.0,17.4574,1.0231,0.07
169,161,REU,Reunion,Saint-Denis,Africa,974052.0,957822.0,922495.0,890130.0,785424.0,658992.0,551674.0,473925.0,2511.0,387.9140,1.0082,0.01
172,76,RWA,Rwanda,Kigali,Africa,13776698.0,13146362.0,11642959.0,10309031.0,8109989.0,7319962.0,5247532.0,3896367.0,26338.0,523.0731,1.0234,0.17
181,187,STP,Sao Tome and Principe,São Tomé,Africa,227380.0,218641.0,201124.0,182138.0,143714.0,120343.0,97210.0,77583.0,964.0,235.8714,1.0192,0.00
183,72,SEN,Senegal,Dakar,Africa,17316449.0,16436119.0,14356181.0,12530121.0,9704287.0,7536001.0,5703869.0,4367744.0,NaN,NaN,1.0261,0.22
185,196,SYC,Seychelles,Victoria,Africa,107118.0,105530.0,99240.0,92409.0,80060.0,71057.0,65290.0,54379.0,452.0,236.9867,1.0061,0.00
186,102,SLE,Sierra Leone,Freetown,Africa,8605718.0,8233969.0,7314773.0,6436698.0,4584067.0,4325388.0,3367477.0,2778557.0,71740.0,119.9570,1.0220,0.11
192,70,SOM,Somalia,Mogadishu,Africa,17597511.0,16537016.0,13763906.0,12026649.0,8721465.0,6999096.0,5892224.0,NaN,637657.0,27.5971,1.0312,0.22
193,24,ZAF,South Africa,Pretoria,Africa,59893885.0,58801927.0,55876504.0,51784921.0,46813266.0,39877570.0,29463549.0,22368306.0,1221037.0,49.0517,1.0084,0.75
195,86,SSD,South Sudan,Juba,Africa,10913164.0,10606227.0,11194299.0,NaN,6114440.0,4750817.0,4192011.0,3342410.0,619745.0,17.6091,1.0153,0.14
198,32,SDN,Sudan,Khartoum,Africa,46874204.0,44440486.0,38171178.0,33739933.0,26298773.0,21090886.0,16673586.0,11305206.0,1886068.0,24.8529,1.0267,0.59
205,22,TZA,Tanzania,Dodoma,Africa,65497748.0,61704518.0,52542823.0,45110527.0,34463704.0,26206012.0,19297659.0,13618192.0,945087.0,69.3034,1.0300,0.82
208,100,TGO,Togo,Lomé,Africa,8848699.0,8442580.0,7473229.0,6571855.0,5008035.0,3875947.0,2838110.0,2197383.0,56785.0,155.8281,1.0236,0.11
212,79,TUN,Tunisia,Tunis,Africa,12356117.0,12161723.0,11557779.0,10895063.0,9893316.0,8440023.0,6578156.0,5047404.0,163610.0,75.5218,1.0076,0.15
217,31,UGA,Uganda,Kampala,Africa,47249585.0,44404611.0,37477356.0,32341728.0,24020697.0,17586630.0,13284026.0,10317212.0,241550.0,195.6100,1.0304,0.59
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [7]:
df[(df['Continent'] == 'Asia') & (df['Rank'] <= 15)]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
102,11,JPN,Japan,Tokyo,Asia,1.239517e+08,1.252448e+08,1.272509e+08,1.281054e+08,1.268039e+08,1.236863e+08,117624196.0,105416839.0,377930.0,327.9753,0.9947,1.55
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
163,13,PHL,Philippines,Manila,Asia,1.155590e+08,1.121910e+08,1.030314e+08,9.463670e+07,7.795822e+07,6.155890e+07,48419546.0,37435586.0,342353.0,337.5434,1.0147,1.45

In [8]:
df[df['Country'].isin (['Egypt', 'Algeria', 'Tunisia'])]
# df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
57,14,EGY,Egypt,Cairo,Africa,110990103.0,107465134.0,97723799.0,87252413.0,71371371.0,57214630.0,43748556.0,34781986.0,1002450.0,110.7188,1.0158,1.39
212,79,TUN,Tunisia,Tunis,Africa,12356117.0,12161723.0,11557779.0,10895063.0,9893316.0,8440023.0,6578156.0,5047404.0,163610.0,75.5218,1.0076,0.15

In [9]:
# .str.contains similiar to like in sql
df[df['Country'].str.contains('United')]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
219,97,ARE,United Arab Emirates,Abu Dhabi,Asia,9441129.0,9287289.0,8916899.0,8481771.0,3275333.0,1900151.0,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
220,21,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
221,3,USA,United States,"Washington, D.C.",North America,338289857.0,335942003.0,324607776.0,311182845.0,282398554.0,248083732.0,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
222,200,VIR,United States Virgin Islands,Charlotte Amalie,North America,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,286.6427,0.9937,0.00

In [10]:
df2 = df.set_index('Country')
df2

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [11]:
df2.filter(items=['Capital', 'CCA3'])

                            Capital CCA3
Country
Afghanistan                   Kabul  AFG
Albania                      Tirana  ALB
Algeria                     Algiers  DZA
American Samoa            Pago Pago  ASM
Andorra            Andorra la Vella  AND
...                             ...  ...
Wallis and Futuna          Mata-Utu  WLF
Western Sahara             El Aaiún  ESH
Yemen                         Sanaa  YEM
Zambia                       Lusaka  ZMB
Zimbabwe                     Harare  ZWE

[234 rows x 2 columns]

In [12]:
df2.filter(like='Alger', axis=0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56

In [13]:
df2.loc['Egypt']

Rank                                    14
CCA3                                   EGY
Capital                              Cairo
Continent                           Africa
2022 Population                110990103.0
2020 Population                107465134.0
2015 Population                 97723799.0
2010 Population                 87252413.0
2000 Population                 71371371.0
1990 Population                 57214630.0
1980 Population                 43748556.0
1970 Population                 34781986.0
Area (km²)                       1002450.0
Density (per km²)                 110.7188
Growth Rate                         1.0158
World Population Percentage           1.39
Name: Egypt, dtype: object

In [14]:
df2.iloc[7]

Rank                                     201
CCA3                                     ATG
Capital                         Saint John’s
Continent                      North America
2022 Population                      93763.0
2020 Population                      92664.0
2015 Population                      89941.0
2010 Population                      85695.0
2000 Population                      75055.0
1990 Population                      63328.0
1980 Population                      64888.0
1970 Population                      64516.0
Area (km²)                             442.0
Density (per km²)                   212.1335
Growth Rate                           1.0058
World Population Percentage              0.0
Name: Antigua and Barbuda, dtype: object

## Ordering

In [15]:
df.sort_values(by='Rank')

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,230,MSR,Montserrat,Brades,North America,4.390000e+03,4.500000e+03,5.059000e+03,4.938000e+03,5.138000e+03,1.080500e+04,11452.0,11402.0,102.0,43.0392,0.9939,0.00
64,231,FLK,Falkland Islands,Stanley,South America,3.780000e+03,3.747000e+03,3.408000e+03,3.187000e+03,3.080000e+03,2.332000e+03,2240.0,2274.0,12173.0,0.3105,1.0043,0.00
150,232,NIU,Niue,Alofi,Oceania,1.934000e+03,1.942000e+03,1.847000e+03,1.812000e+03,2.074000e+03,2.533000e+03,3637.0,5185.0,260.0,7.4385,0.9985,0.00
209,233,TKL,Tokelau,Nukunonu,Oceania,1.871000e+03,1.827000e+03,1.454000e+03,1.367000e+03,1.666000e+03,1.669000e+03,1647.0,1714.0,12.0,155.9167,1.0119,0.00
226,234,VAT,Vatican City,Vatican City,Europe,5.100000e+02,5.200000e+02,5.640000e+02,5.960000e+02,6.510000e+02,7.000000e+02,733.0,752.0,1.0,510.0000,0.9980,0.00

In [16]:
df.sort_values(by=['Continent', 'Country'])

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
5,42,AGO,Angola,Luanda,Africa,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
21,77,BEN,Benin,Porto-Novo,Africa,13352864.0,12643123.0,10932783.0,9445710.0,6998023.0,5133419.0,3833939.0,3023443.0,112622.0,118.5635,1.0274,0.17
26,144,BWA,Botswana,Gaborone,Africa,2630296.0,2546402.0,2305171.0,2091664.0,1726985.0,1341474.0,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
31,58,BFA,Burkina Faso,Ouagadougou,Africa,22673762.0,21522626.0,18718019.0,16116845.0,11882888.0,9131361.0,6932967.0,5611666.0,272967.0,83.0641,1.0259,0.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,109,PRY,Paraguay,Asunción,South America,6780744.0,6618695.0,6177950.0,5768613.0,5123819.0,4059195.0,3078912.0,2408787.0,406752.0,16.6705,1.0115,0.09
162,44,PER,Peru,Lima,South America,34049588.0,33304756.0,30711863.0,29229572.0,26654439.0,22109099.0,17492406.0,13562371.0,1285216.0,26.4933,1.0099,0.43
199,170,SUR,Suriname,Paramaribo,South America,618040.0,607065.0,575475.0,546080.0,478998.0,412756.0,375112.0,379918.0,163820.0,3.7727,1.0082,0.01
223,133,URY,Uruguay,Montevideo,South America,3422794.0,3429086.0,3402818.0,3352651.0,3292224.0,3117012.0,2953750.0,2790265.0,181034.0,18.9069,0.9990,0.04
227,51,VEN,Venezuela,Caracas,South America,28301696.0,28490453.0,30529716.0,28715022.0,NaN,19750579.0,15210443.0,11355475.0,NaN,30.8820,1.0036,0.35

In [17]:
df.sort_values(by=['Continent', 'Country'], ascending=False)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
227,51,VEN,Venezuela,Caracas,South America,28301696.0,28490453.0,30529716.0,28715022.0,NaN,19750579.0,15210443.0,11355475.0,NaN,30.8820,1.0036,0.35
223,133,URY,Uruguay,Montevideo,South America,3422794.0,3429086.0,3402818.0,3352651.0,3292224.0,3117012.0,2953750.0,2790265.0,181034.0,18.9069,0.9990,0.04
199,170,SUR,Suriname,Paramaribo,South America,618040.0,607065.0,575475.0,546080.0,478998.0,412756.0,375112.0,379918.0,163820.0,3.7727,1.0082,0.01
162,44,PER,Peru,Lima,South America,34049588.0,33304756.0,30711863.0,29229572.0,26654439.0,22109099.0,17492406.0,13562371.0,1285216.0,26.4933,1.0099,0.43
161,109,PRY,Paraguay,Asunción,South America,6780744.0,6618695.0,6177950.0,5768613.0,5123819.0,4059195.0,3078912.0,2408787.0,406752.0,16.6705,1.0115,0.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,58,BFA,Burkina Faso,Ouagadougou,Africa,22673762.0,21522626.0,18718019.0,16116845.0,11882888.0,9131361.0,6932967.0,5611666.0,272967.0,83.0641,1.0259,0.28
26,144,BWA,Botswana,Gaborone,Africa,2630296.0,2546402.0,2305171.0,2091664.0,1726985.0,1341474.0,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
21,77,BEN,Benin,Porto-Novo,Africa,13352864.0,12643123.0,10932783.0,9445710.0,6998023.0,5133419.0,3833939.0,3023443.0,112622.0,118.5635,1.0274,0.17
5,42,AGO,Angola,Luanda,Africa,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56

In [18]:
df[(df['Rank'] < 25) & (df['Continent'] == 'Africa')].sort_values(by=['Rank'])

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
149,6,NGA,Nigeria,Abuja,Africa,218541212.0,208327405.0,183995785.0,160952853.0,122851984.0,95214257.0,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
63,12,ETH,Ethiopia,Addis Ababa,Africa,123379924.0,117190911.0,102471895.0,89237791.0,67031867.0,47878073.0,34945469.0,28308246.0,1104300.0,111.7268,1.0257,1.55
57,14,EGY,Egypt,Cairo,Africa,110990103.0,107465134.0,97723799.0,87252413.0,71371371.0,57214630.0,43748556.0,34781986.0,1002450.0,110.7188,1.0158,1.39
55,15,COD,DR Congo,Kinshasa,Africa,99010212.0,92853164.0,78656904.0,66391257.0,48616317.0,35987541.0,26708686.0,20151733.0,2344858.0,42.2244,1.0325,1.24
205,22,TZA,Tanzania,Dodoma,Africa,65497748.0,61704518.0,52542823.0,45110527.0,34463704.0,26206012.0,19297659.0,13618192.0,945087.0,69.3034,1.0300,0.82
193,24,ZAF,South Africa,Pretoria,Africa,59893885.0,58801927.0,55876504.0,51784921.0,46813266.0,39877570.0,29463549.0,22368306.0,1221037.0,49.0517,1.0084,0.75

## **Indexing**

In [19]:
#1
df2 = pd.read_csv('/content/world_population.csv', index_col='Country')
df2

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [20]:
# to reset index
df2.reset_index(inplace=True)
df2

,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [21]:
#2

df2.set_index('Country', inplace=True)
df2.head()

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [22]:
# df2.reset_index(inplace=True)
# df2.head()

In [23]:
# loc and iloc


df2.loc['Algeria']    # label

Rank                                   34
CCA3                                  DZA
Capital                           Algiers
Continent                          Africa
2022 Population                44903225.0
2020 Population                43451666.0
2015 Population                39543154.0
2010 Population                35856344.0
2000 Population                30774621.0
1990 Population                25518074.0
1980 Population                18739378.0
1970 Population                13795915.0
Area (km²)                      2381741.0
Density (per km²)                 18.8531
Growth Rate                        1.0164
World Population Percentage          0.56
Name: Algeria, dtype: object

In [24]:
df2.iloc[2]  #int location

Rank                                   34
CCA3                                  DZA
Capital                           Algiers
Continent                          Africa
2022 Population                44903225.0
2020 Population                43451666.0
2015 Population                39543154.0
2010 Population                35856344.0
2000 Population                30774621.0
1990 Population                25518074.0
1980 Population                18739378.0
1970 Population                13795915.0
Area (km²)                      2381741.0
Density (per km²)                 18.8531
Growth Rate                        1.0164
World Population Percentage          0.56
Name: Algeria, dtype: object

### Multi index

In [25]:
df2.reset_index(inplace=True)


df2.set_index(['Continent', 'Country'], inplace=True)
df2.head()

,,Rank,CCA3,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Continent,Country,,,,,,,,,,,,,,,
Asia,Afghanistan,36,AFG,Kabul,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Europe,Albania,138,ALB,Tirana,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Africa,Algeria,34,DZA,Algiers,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
Oceania,American Samoa,213,ASM,Pago Pago,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Europe,Andorra,203,AND,Andorra la Vella,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [26]:
df2.sort_index(inplace=True, ascending=True)
df2

                            Rank CCA3      Capital  2022 Population  \
Continent     Country
Africa        Algeria         34  DZA      Algiers       44903225.0
              Angola          42  AGO       Luanda       35588987.0
              Benin           77  BEN   Porto-Novo       13352864.0
              Botswana       144  BWA     Gaborone        2630296.0
              Burkina Faso    58  BFA  Ouagadougou       22673762.0
...                          ...  ...          ...              ...
South America Paraguay       109  PRY     Asunción        6780744.0
              Peru            44  PER         Lima       34049588.0
              Suriname       170  SUR   Paramaribo         618040.0
              Uruguay        133  URY   Montevideo        3422794.0
              Venezuela       51  VEN      Caracas       28301696.0

                            2020 Population  2015 Population  2010 Population  \
Continent     Country
Africa        Algeria            43451666.0       39543154.0       35856344.0
              Angola             33428485.0       28127721.0       23364185.0
              Benin              12643123.0       10932783.0        9445710.0
              Botswana            2546402.0        2305171.0        2091664.0
              Burkina Faso       21522626.0       18718019.0       16116845.0
...                                     ...              ...              ...
South America Paraguay            6618695.0        6177950.0        5768613.0
              Peru               33304756.0       30711863.0       29229572.0
              Suriname             607065.0         575475.0         546080.0
              Uruguay             3429086.0        3402818.0        3352651.0
              Venezuela          28490453.0       30529716.0       28715022.0

                            2000 Population  1990 Population  1980 Population  \
Continent     Country
Africa        Algeria            30774621.0       25518074.0       18739378.0
              Angola             16394062.0       11828638.0        8330047.0
              Benin               6998023.0        5133419.0        3833939.0
              Botswana            1726985.0        1341474.0         938578.0
              Burkina Faso       11882888.0        9131361.0        6932967.0
...                                     ...              ...              ...
South America Paraguay            5123819.0        4059195.0        3078912.0
              Peru               26654439.0       22109099.0       17492406.0
              Suriname             478998.0         412756.0         375112.0
              Uruguay             3292224.0        3117012.0        2953750.0
              Venezuela                 NaN       19750579.0       15210443.0

                            1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
Africa        Algeria            13795915.0   2381741.0            18.8531
              Angola              6029700.0   1246700.0            28.5466
              Benin               3023443.0    112622.0           118.5635
              Botswana             592244.0    582000.0             4.5194
              Burkina Faso        5611666.0    272967.0            83.0641
...                                     ...         ...                ...
South America Paraguay            2408787.0    406752.0            16.6705
              Peru               13562371.0   1285216.0            26.4933
              Suriname             379918.0    163820.0             3.7727
              Uruguay             2790265.0    181034.0            18.9069
              Venezuela          11355475.0         NaN            30.8820

                            Growth Rate  World Population Percentage
Continent     Country
Africa        Algeria            1.0164                         0.56
              Angola             1.0315                         0.45
              Benin              1.0274                         0.17
              Botswana           1.0162                         0.03
              Burkina Faso       1.0259                         0.28
...                                 ...                          ...
South America Paraguay           1.0115                         0.09
              Peru               1.0099                         0.43
              Suriname           1.0082                         0.01
              Uruguay            0.9990                         0.04
              Venezuela          1.0036                         0.35

[234 rows x 15 columns]

In [27]:
df2.loc['Africa']

,Rank,CCA3,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,
Algeria,34,DZA,Algiers,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
Angola,42,AGO,Luanda,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
Benin,77,BEN,Porto-Novo,13352864.0,12643123.0,10932783.0,9445710.0,6998023.0,5133419.0,3833939.0,3023443.0,112622.0,118.5635,1.0274,0.17
Botswana,144,BWA,Gaborone,2630296.0,2546402.0,2305171.0,2091664.0,1726985.0,1341474.0,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
Burkina Faso,58,BFA,Ouagadougou,22673762.0,21522626.0,18718019.0,16116845.0,11882888.0,9131361.0,6932967.0,5611666.0,272967.0,83.0641,1.0259,0.28
Burundi,78,BDI,Bujumbura,12889576.0,12220227.0,10727148.0,9126605.0,6307659.0,5483793.0,4312834.0,3497834.0,27834.0,463.0874,1.0270,0.16
Cameroon,53,CMR,Yaounde,27914536.0,26491087.0,23012646.0,19878036.0,15091594.0,11430520.0,8519891.0,6452787.0,475442.0,58.7128,1.0263,0.35
Cape Verde,171,CPV,Praia,593149.0,582640.0,552166.0,521212.0,458251.0,364563.0,317234.0,287262.0,4033.0,147.0739,1.0089,0.01
Central African Republic,117,CAF,Bangui,5579144.0,5343020.0,4819333.0,4660067.0,3759170.0,2809221.0,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07
Chad,69,TCD,N'Djamena,17723315.0,16644701.0,14140274.0,11894727.0,8259137.0,5827069.0,4408230.0,3667394.0,1284000.0,13.8032,1.0316,0.22
Comoros,163,COM,Moroni,836774.0,806166.0,730216.0,656024.0,536758.0,431119.0,328328.0,242351.0,1862.0,449.3953,1.0184,0.01
DR Congo,15,COD,Kinshasa,99010212.0,92853164.0,78656904.0,66391257.0,48616317.0,35987541.0,26708686.0,20151733.0,2344858.0,42.2244,1.0325,1.24
Djibouti,160,DJI,Djibouti,1120849.0,1090156.0,1006259.0,919199.0,742033.0,577173.0,324121.0,144379.0,23200.0,48.3125,1.0138,0.01
Egypt,14,EGY,Cairo,110990103.0,107465134.0,97723799.0,87252413.0,71371371.0,57214630.0,43748556.0,34781986.0,1002450.0,110.7188,1.0158,1.39
Equatorial Guinea,152,GNQ,Malabo,1674908.0,1596049.0,NaN,1094524.0,684977.0,465549.0,282509.0,316955.0,28051.0,59.7094,1.0247,0.02
Eritrea,132,ERI,Asmara,3684032.0,3555868.0,3340006.0,3147727.0,2392880.0,2149960.0,1657982.0,1272748.0,117600.0,31.3268,1.0176,0.05
Eswatini,159,SWZ,Mbabane,NaN,1180655.0,1133936.0,1099920.0,1030496.0,854011.0,598564.0,442865.0,17364.0,69.2047,1.0079,0.02
Ethiopia,12,ETH,Addis Ababa,123379924.0,117190911.0,102471895.0,89237791.0,67031867.0,47878073.0,34945469.0,28308246.0,1104300.0,111.7268,1.0257,1.55
Gabon,146,GAB,Libreville,2388992.0,2292573.0,2028517.0,1711105.0,1272935.0,983028.0,749078.0,597192.0,267668.0,8.9252,1.0204,0.03
Gambia,142,GMB,Banjul,2705992.0,2573995.0,2253133.0,NaN,NaN,NaN,NaN,NaN,10689.0,253.1567,1.0250,0.03
Ghana,47,GHA,Accra,33475870.0,32180401.0,28870939.0,25574719.0,19665502.0,15446982.0,11865246.0,8861895.0,238533.0,140.3406,1.0196,0.42
Guinea,75,GIN,Conakry,13859341.0,13205153.0,11625998.0,10270728.0,8336967.0,6354145.0,4972609.0,4222374.0,245857.0,56.3716,1.0242,0.17
Guinea-Bissau,149,GNB,Bissau,2105566.0,2015828.0,1788919.0,1567220.0,1230849.0,973551.0,831462.0,591663.0,36125.0,58.2856,1.0218,0.03
Ivory Coast,52,CIV,Yamoussoukro,28160542.0,26811790.0,23596741.0,21120042.0,16799670.0,11910540.0,8303809.0,5477086.0,322463.0,NaN,NaN,0.35
Kenya,27,KEN,Nairobi,54027487.0,51985780.0,46851488.0,41517895.0,30851606.0,23162269.0,16187124.0,11473087.0,580367.0,93.0919,1.0193,0.68
Lesotho,147,LSO,Maseru,2305825.0,2254100.0,2118521.0,2022747.0,1998630.0,1798997.0,1407672.0,1023481.0,30355.0,75.9620,1.0107,0.03
Liberia,121,LBR,Monrovia,5302681.0,5087584.0,4612329.0,4019956.0,2895224.0,2209731.0,1932169.0,1463563.0,111369.0,47.6136,1.0210,0.07
Libya,107,LBY,Tripoli,6812341.0,6653942.0,6192235.0,6491988.0,5154790.0,4236983.0,2962720.0,1909177.0,1759540.0,3.8717,1.0114,0.09
Madagascar,50,MDG,Antananarivo,29611714.0,28225177.0,24850912.0,21731053.0,16216431.0,11882762.0,8948162.0,6639751.0,587041.0,50.4423,1.0241,0.37
Malawi,62,MWI,Lilongwe,20405317.0,19377061.0,16938942.0,14718422.0,11229387.0,9539665.0,6267369.0,4625141.0,118484.0,172.2200,1.0259,0.26
Mali,59,MLI,Bamako,22593590.0,21224040.0,18112907.0,15529181.0,11239101.0,8945026.0,7372581.0,6153587.0,1240192.0,18.2178,1.0314,0.28
Mauritania,126,MRT,Nouakchott,4736139.0,4498604.0,3946220.0,3419461.0,2695003.0,2006027.0,1506694.0,1122198.0,1030700.0,4.5951,1.0263,0.06
Mauritius,157,MUS,Port Louis,1299469.0,1297828.0,1293153.0,1283330.0,1215930.0,1090290.0,954865.0,830115.0,2040.0,636.9946,1.0004,0.02
Mayotte,182,MYT,Mamoudzou,326101.0,305587.0,249545.0,211786.0,159215.0,92659.0,52233.0,35383.0,374.0,871.9278,1.0319,0.00
Morocco,40,MAR,Rabat,37457971.0,36688772.0,34680458.0,32464865.0,28554415.0,24570814.0,19678444.0,15274351.0,446550.0,83.8830,1.0103,0.47
Mozambique,48,MOZ,Maputo,32969517.0,31178239.0,NaN,NaN,17768505.0,13303459.0,11413587.0,8411676.0,801590.0,41.1302,1.0278,0.41
Namibia,145,NAM,Windhoek,2567012.0,2489098.0,2282704.0,2099271.0,1819141.0,1369011.0,975994.0,754467.0,825615.0,3.1092,1.0146,0.03
Niger,54,NER,Niamey,26207977.0,24333639.0,20128124.0,16647543.0,11622665.0,8370647.0,6173177.0,4669708.0,1267000.0,20.6851,1.0378,0.33
Nigeria,6,NGA,Abuja,218541212.0,208327405.0,183995785.0,160952853.0,122851984.0,95214257.0,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
Republic of the Congo,114,COG,Brazzaville,5970424.0,5702174.0,5064386.0,4437884.0,3134030.0,2385435.0,1829256.0,1396989.0,342000.0,17.4574,1.0231,0.07
Reunion,161,REU,Saint-Denis,974052.0,957822.0,922495.0,890130.0,785424.0,658992.0,551674.0,473925.0,2511.0,387.9140,1.0082,0.01
Rwanda,76,RWA,Kigali,13776698.0,13146362.0,11642959.0,10309031.0,8109989.0,7319962.0,5247532.0,3896367.0,26338.0,523.0731,1.0234,0.17
Sao Tome and Principe,187,STP,São Tomé,227380.0,218641.0,201124.0,182138.0,143714.0,120343.0,97210.0,77583.0,964.0,235.8714,1.0192,0.00
Senegal,72,SEN,Dakar,17316449.0,16436119.0,14356181.0,12530121.0,9704287.0,7536001.0,5703869.0,4367744.0,NaN,NaN,1.0261,0.22
Seychelles,196,SYC,Victoria,107118.0,105530.0,99240.0,92409.0,80060.0,71057.0,65290.0,54379.0,452.0,236.9867,1.0061,0.00
Sierra Leone,102,SLE,Freetown,8605718.0,8233969.0,7314773.0,6436698.0,4584067.0,4325388.0,3367477.0,2778557.0,71740.0,119.9570,1.0220,0.11
Somalia,70,SOM,Mogadishu,17597511.0,16537016.0,13763906.0,12026649.0,8721465.0,6999096.0,5892224.0,NaN,637657.0,27.5971,1.0312,0.22
South Africa,24,ZAF,Pretoria,59893885.0,58801927.0,55876504.0,51784921.0,46813266.0,39877570.0,29463549.0,22368306.0,1221037.0,49.0517,1.0084,0.75
South Sudan,86,SSD,Juba,10913164.0,10606227.0,11194299.0,NaN,6114440.0,4750817.0,4192011.0,3342410.0,619745.0,17.6091,1.0153,0.14
Sudan,32,SDN,Khartoum,46874204.0,44440486.0,38171178.0,33739933.0,26298773.0,21090886.0,16673586.0,11305206.0,1886068.0,24.8529,1.0267,0.59
Tanzania,22,TZA,Dodoma,65497748.0,61704518.0,52542823.0,45110527.0,34463704.0,26206012.0,19297659.0,13618192.0,945087.0,69.3034,1.0300,0.82
Togo,100,TGO,Lomé,8848699.0,8442580.0,7473229.0,6571855.0,5008035.0,3875947.0,2838110.0,2197383.0,56785.0,155.8281,1.0236,0.11
Tunisia,79,TUN,Tunis,12356117.0,12161723.0,11557779.0,10895063.0,9893316.0,8440023.0,6578156.0,5047404.0,163610.0,75.5218,1.0076,0.15
Uganda,31,UGA,Kampala,47249585.0,44404611.0,37477356.0,32341728.0,24020697.0,17586630.0,13284026.0,10317212.0,241550.0,195.6100,1.0304,0.59
Western Sahara,172,ESH,El Aaiún,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Zambia,63,ZMB,Lusaka,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [28]:
df2.loc['Africa', 'Egypt']

Rank                                    14
CCA3                                   EGY
Capital                              Cairo
2022 Population                110990103.0
2020 Population                107465134.0
2015 Population                 97723799.0
2010 Population                 87252413.0
2000 Population                 71371371.0
1990 Population                 57214630.0
1980 Population                 43748556.0
1970 Population                 34781986.0
Area (km²)                       1002450.0
Density (per km²)                 110.7188
Growth Rate                         1.0158
World Population Percentage           1.39
Name: (Africa, Egypt), dtype: object

## Group By and Aggregate Functions

In [44]:
dff = pd.read_csv('https://raw.githubusercontent.com/amrutakulkarni9812/Stack-Overflow-Developer-Survey-Analysis/master/survey-results-public.csv')
dff.head()

,Respondent,Professional,ProgramHobby,Country,University,EmploymentStatus,FormalEducation,MajorUndergrad,HomeRemote,CompanySize,CompanyType,YearsProgram,YearsCodedJob,YearsCodedJobPast,DeveloperType,WebDeveloperType,MobileDeveloperType,NonDeveloperType,CareerSatisfaction,JobSatisfaction,ExCoderReturn,ExCoderNotForMe,ExCoderBalance,ExCoder10Years,ExCoderBelonged,ExCoderSkills,ExCoderWillNotCode,ExCoderActive,PronounceGIF,ProblemSolving,BuildingThings,LearningNewTech,BoringDetails,JobSecurity,DiversityImportant,AnnoyingUI,FriendsDevelopers,RightWrongWay,UnderstandComputers,SeriousWork,InvestTimeTools,WorkPayCare,KinshipDevelopers,ChallengeMyself,CompetePeers,ChangeWorld,JobSeekingStatus,HoursPerWeek,LastNewJob,AssessJobIndustry,AssessJobRole,AssessJobExp,AssessJobDept,AssessJobTech,AssessJobProjects,AssessJobCompensation,AssessJobOffice,AssessJobCommute,AssessJobRemote,AssessJobLeaders,AssessJobProfDevel,AssessJobDiversity,AssessJobProduct,AssessJobFinances,ImportantBenefits,ClickyKeys,JobProfile,ResumePrompted,LearnedHiring,ImportantHiringAlgorithms,ImportantHiringTechExp,ImportantHiringCommunication,ImportantHiringOpenSource,ImportantHiringPMExp,ImportantHiringCompanies,ImportantHiringTitles,ImportantHiringEducation,ImportantHiringRep,ImportantHiringGettingThingsDone,Currency,Overpaid,TabsSpaces,EducationImportant,EducationTypes,SelfTaughtTypes,TimeAfterBootcamp,CousinEducation,WorkStart,HaveWorkedLanguage,WantWorkLanguage,HaveWorkedFramework,WantWorkFramework,HaveWorkedDatabase,WantWorkDatabase,HaveWorkedPlatform,WantWorkPlatform,IDE,AuditoryEnvironment,Methodology,VersionControl,CheckInCode,ShipIt,OtherPeoplesCode,ProjectManagement,EnjoyDebugging,InTheZone,DifficultCommunication,CollaborateRemote,MetricAssess,EquipmentSatisfiedMonitors,EquipmentSatisfiedCPU,EquipmentSatisfiedRAM,EquipmentSatisfiedStorage,EquipmentSatisfiedRW,InfluenceInternet,InfluenceWorkstation,InfluenceHardware,InfluenceServers,InfluenceTechStack,InfluenceDeptTech,InfluenceVizTools,InfluenceDatabase,InfluenceCloud,InfluenceConsultants,InfluenceRecruitment,InfluenceCommunication,StackOverflowDescribes,StackOverflowSatisfaction,StackOverflowDevices,StackOverflowFoundAnswer,StackOverflowCopiedCode,StackOverflowJobListing,StackOverflowCompanyPage,StackOverflowJobSearch,StackOverflowNewQuestion,StackOverflowAnswer,StackOverflowMetaChat,StackOverflowAdsRelevant,StackOverflowAdsDistracting,StackOverflowModeration,StackOverflowCommunity,StackOverflowHelpful,StackOverflowBetter,StackOverflowWhatDo,StackOverflowMakeMoney,Gender,HighestEducationParents,Race,SurveyLong,QuestionsInteresting,QuestionsConfusing,InterestedAnswers,Salary,ExpectedSalary
0,1,Student,"Yes, both",United States,No,"Not employed, and not looking for work",Secondary school,NaN,NaN,NaN,NaN,2 to 3 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"With a soft ""g,"" like ""jiff""",Strongly agree,Strongly agree,Agree,Disagree,Strongly agree,Agree,Agree,Disagree,Somewhat agree,Disagree,Strongly agree,Strongly agree,Strongly disagree,Agree,Agree,Disagree,Agree,"I'm not actively looking, but I am open to new...",0.0,Not applicable/ never,Very important,Very important,Important,Very important,Very important,Very important,Important,Very important,Very important,Very important,Very important,Very important,Somewhat important,Not very important,Somewhat important,Stock options; Vacation/days off; Remote options,Yes,Other,NaN,NaN,Important,Important,Important,Somewhat important,Important,Not very important,Not very important,Not at all important,Somewhat important,Very important,NaN,NaN,Tabs,NaN,Online course; Open source contributions,NaN,NaN,NaN,6:00 AM,Swift,Swift,NaN,NaN,NaN,NaN,iOS,iOS,Atom; Xcode,Turn on some music,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Somewhat satisfied,Not very satisfied,Not at all satisfied,Very satisfied,Satisfied,Not very satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have created a CV or Developer Story on Stac...,9.0,Desktop; iOS app,At least once each week,Haven't done at all,Once or twice,Haven't done at all,Haven't done at all,Several times,Several times,Once or twice,Somewhat agree,Strongly disagree,Strongly disagree,Strongly agree,Agree,Strongly agree,Strongly agree,Strongly disagree,Male,High school,White or of European descent,Strongly disagree,Strongly agree,Disagree,Strongly agree,NaN,NaN
1,2,Student,"Yes, both",United Kingdom,"Yes, full-time",Employed part-time,Some college/university study without earning ...,Computer science or software engineering,"More than half, but not all, the time",20 to 99 employees,"Privately-held limited company, not in startup...",9 to 10 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"With a hard ""g,"" like ""gift""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Other,NaN,Some other way,Important,Important,Important,Important,Somewhat important,Somewhat important,Not very important,Somewhat important,Not very important,Very important,British pounds sterling (£),NaN,Spaces,NaN,Online course; Self-taught; Hackathon; Open so...,Official documentation; Stack Overflow Q&A; Other,NaN,NaN,10:00 AM,JavaScript; Python; Ruby; SQL,Java; Python; Ruby; SQL,.NET Core,.NET Core,MySQL; SQLite,MySQL; SQLite,Amazon Web Services (AWS),Linux Desktop; Raspberry Pi; Amazon Web Servic...,Atom; Notepad++; Vim; PyCharm; RubyMine; Visua...,"Put on some ambient sounds (e.g. whale songs, ...",NaN,Git,Multiple times a day,Agree,Disagree,Strongly disagree,Agree,Somewhat agree,Disagree,Strongly disagree,Customer satisfaction; On time/in budget; Peer...,Not very satisfied,Satisfied,Satisfied,Satisfied,Somewhat satisfied,Satisfied,No influence at all,No influence at all,No influence at all,No influence at all,No influence at all,No influence at all,No influence at all,No influence at all,No influence at all,No influence at all,No influence at all,I have created a CV or Developer Story on Stac...,8.0,Desktop; iOS browser; iOS app; Android browser...,Several times,Several times,Once or twice,Once or twice,Once or twice,Haven't done at all,Several times,At least once each week,Disagree,Strongly disagree,Strongly disagree,Strongly agree,Agree,Strongly agree,Strongly agree,Strongly disagree,Male,A master's degree,White or of European descent,Somewhat agree,Somewhat agree,Disagree,Strongly agree,NaN,37500.0
2,3,Professional developer,"Yes, both",United Kingdom,No,Employed full-time,Bachelor's degree,Computer science or software engineering,"Less than half the time, but at least one day ...","10,000 or more employees",Publicly-traded corporation,20 or more years,20 or more years,NaN,Other,NaN,NaN,NaN,8.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"With a hard ""g,"" like ""gift""",Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Agree,Strongly agree,Agree,Somewhat agree,Disagree,Disagree,Agree,Somewhat agree,Disagree,Somewhat agree,Agree,Disagree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,British pounds sterling (£),Neither underpaid nor overpaid,Spaces,Not very important,Self-taught; Coding competition; Hackathon; Op...,Official documentation; Trade book; Textbook; ...,NaN,NaN,9:00 AM,Java; PHP; Python,C; Python; Rust,NaN,NaN,MySQL,NaN,NaN,NaN,Sublime Text; Vim; IntelliJ,Turn on some music,Agile; Lean; Scrum; Extreme; Pair; Kanban,Mercurial,Multiple times a day,Agree,Disagree,Disagree,Agree,Agree,Disagree,Somewhat agree,Customer satisfaction; Benchmarked product per...,Very satisfied,Somewhat satisfied,Satisfied,Satisfied,Somewhat satisfied,Very satisfied,A lot of influence,Some influence,Some influence,Some influence,A lot of influence,Some influence,Some influence,Some influence,Some influence,Some influence,Some influence,I have created a CV or Developer Story on Stac...,8.0,Desktop; iOS browser; iOS app,Once or twice,Haven't done at all,Haven't done at all,Haven't done at all,Haven't done at all,Haven't done at all,At least once each day,At least once each day,Disagree,Disagree,Strongly disagree,Strongly agree,Agree,Agree,Agree,Disagree,Male,A professional degree,White or of European descent,Somewhat agree,Agree,Disagree,Agree,113750.0,NaN
3,4,Professional non-developer who sometimes write...,"Yes, both",United States,No,Employed full-time,Doctoral degree,A non-computer-focused engineering discipline,"Less than half the time, but at least one day ...","10,000 or more employees",Non-profit/non-governmental organization or pr...,14 to 15 years,9 to 10 years,NaN,NaN,NaN,NaN,Data scientist,6.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"With a soft ""g,"" like ""jiff""",Strongly agree,Strongly agree,Strongly agree,Disagree,Somewhat agree,Agree,Agree,Agree,Somewhat agree,Strongly disagree,Strongly agree,Agree,Disagree,Strongly agree,Strongly agree,Somewhat agree,Agree,I am actively looking for a job,5.0,Between 2 and 4 years ago,Somewhat important,Somewhat important,Somewhat important,Important,Important,Very important,Important,Very important,Important,Somewhat important,Not very important,Very important,Important,Very important,Very important,Stock options; Annual bonus; Health benefits; ...,Yes,LinkedIn; Other,NaN,"A friend, family member, or former colleague t...",Somewhat important,Somewhat important,Very important,Very important,Somewhat important,Somewhat important,Not very important,Not very important,Important,Very important,NaN,NaN,Spaces,NaN,NaN,NaN,NaN,NaN,9:00 AM,Matlab; Python; R; SQL,Matlab; Python; R; SQL,React,Hadoop; Node.js; React,MongoDB; Redis; SQL Server; MySQL; SQLite,MongoDB; Redis; SQL Server; MySQL; SQLite,Windows Desktop; Linux Desktop; Mac OS; Amazon...,Windows Desktop; Linux Desktop; Mac OS; Amazon...,Notepad++; Sublime Text; TextMate; Vim; IPytho...,Turn on some music,Agile,Git,Multiple times a day,Somewhat agree,Agree,Somewhat agree,Somewhat agree,Strongly agree,Disagree,Somewhat agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have created a CV or Developer Story on Stac...,10.0,Desktop; iOS browser; iOS app,At least once each week,Several times,At least once each week,Several times,At least once each week,Several times,At least once each day,At least once each day,Agree,Strongly disagree,Strongly disagree,Strongly agree,Strongly agree,Agree,Strongly agree,Disagree,Male,A doctoral degree,White or of European descent,Agree,Agree,Somewhat agree,Strongly agree,NaN,NaN
4,5,Professional developer,"Yes, I program as a hobby",Switzerland,No,Employed full-time,Master's degree,Computer science or software engineering,Never,10 to 19 employees,"Privately-held limited company, not in startup...",20 or more years,10 to 11 years,NaN,Mobile developer; Graphics programming; Deskto...,NaN,NaN,NaN,6.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"With a soft ""g,"" like ""jiff""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Satisfied,Satisfied,Satisfied,Satisfied,Satisfied,Satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51392 entries, 0 to 51391
Columns: 154 entries, Respondent to ExpectedSalary
dtypes: float64(6), int64(1), object(147)
memory usage: 60.4+ MB

In [50]:
dff.describe()

,Respondent,CareerSatisfaction,JobSatisfaction,HoursPerWeek,StackOverflowSatisfaction,Salary,ExpectedSalary
count,51392.000000,42695.000000,40376.000000,20600.000000,36592.000000,12891.000000,2566.000000
mean,25696.500000,7.300574,6.957078,3.952282,8.429875,56298.480641,33142.220468
std,14835.736854,1.955444,2.167652,7.564722,1.390635,39880.905277,30162.988829
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,12848.750000,6.000000,6.000000,1.000000,8.000000,26440.371839,4490.492484
50%,25696.500000,8.000000,7.000000,1.000000,9.000000,50000.000000,29364.263691
75%,38544.250000,9.000000,8.000000,4.000000,10.000000,80000.000000,50403.225806
max,51392.000000,10.000000,10.000000,40.000000,10.000000,197000.000000,187500.000000

In [48]:
#dff['Salary'].median()
#dff['Salary'].mean()

50000.0

In [52]:
dff['VersionControl'].value_counts()

VersionControl
Git                                            21266
Subversion                                      2790
Team Foundation Server                          2255
I don't use version control                     1468
I use some other system                          924
Zip file back-ups                                609
Mercurial                                        591
Copying and pasting files to network shares      510
Visual Source Safe                               196
Rational ClearCase                               121
Name: count, dtype: int64

In [53]:
dff['Gender'].value_counts()

Gender
Male                                                       31589
Female                                                      2600
Other                                                        225
Male; Other                                                  171
Gender non-conforming                                        160
Male; Gender non-conforming                                   65
Female; Transgender                                           56
Transgender                                                   55
Female; Gender non-conforming                                 29
Male; Female                                                  15
Transgender; Gender non-conforming                            15
Male; Female; Transgender; Gender non-conforming; Other       15
Male; Transgender                                             11
Female; Transgender; Gender non-conforming                     8
Male; Female; Transgender; Gender non-conforming               7
Male; Female; Transgender                                      4
Gender non-conforming; Other                                   4
Male; Transgender; Gender non-conforming                       4
Male; Gender non-conforming; Other                             3
Male; Female; Other                                            2
Male; Female; Gender non-conforming                            1
Female; Other                                                  1
Transgender; Other                                             1
Female; Gender non-conforming; Other                           1
Male; Female; Gender non-conforming; Other                     1
Female; Transgender; Other                                     1
Female; Transgender; Gender non-conforming; Other              1
Male; Transgender; Other                                       1
Male; Female; Transgender; Other                               1
Name: count, dtype: int64

In [56]:
xx = dff['IDE'].value_counts()
xx[xx > 1000]

IDE
Notepad++; Visual Studio    1624
Visual Studio               1566
Vim                         1217
Name: count, dtype: int64

In [68]:
zz = dff['HaveWorkedLanguage'].value_counts()
zz[(zz.index.str.contains('Python'))]

HaveWorkedLanguage
Python                                                                                                              529
JavaScript; Python                                                                                                  384
JavaScript; PHP; Python; SQL                                                                                        253
Java; Python                                                                                                        207
JavaScript; Python; SQL                                                                                             203
                                                                                                                   ...
Assembly; C; Java; JavaScript; Python; SQL; TypeScript                                                                1
C; C++; CoffeeScript; Common Lisp; Go; Haskell; Java; JavaScript; Perl; PHP; Python; R; Ruby; SQL; Swift; VB.NET      1
C; C++; C#; Go; Java; JavaScript; Perl; PHP; Python; SQL                                                              1
C++; Lua; Perl; Python; SQL                                                                                           1
C#; JavaScript; PHP; Python; R; SQL                                                                                   1
Name: count, Length: 4163, dtype: int64

In [70]:
zz[(zz.index.str.contains('Python'))].sum()

11704

**Group by =>  [split]  => [applay Function]  => [combine results]**

In [71]:
country_grp = dff.groupby('Country')

In [73]:
country_grp.get_group('Egypt').head(5)

,Respondent,Professional,ProgramHobby,Country,University,EmploymentStatus,FormalEducation,MajorUndergrad,HomeRemote,CompanySize,CompanyType,YearsProgram,YearsCodedJob,YearsCodedJobPast,DeveloperType,WebDeveloperType,MobileDeveloperType,NonDeveloperType,CareerSatisfaction,JobSatisfaction,ExCoderReturn,ExCoderNotForMe,ExCoderBalance,ExCoder10Years,ExCoderBelonged,ExCoderSkills,ExCoderWillNotCode,ExCoderActive,PronounceGIF,ProblemSolving,BuildingThings,LearningNewTech,BoringDetails,JobSecurity,DiversityImportant,AnnoyingUI,FriendsDevelopers,RightWrongWay,UnderstandComputers,SeriousWork,InvestTimeTools,WorkPayCare,KinshipDevelopers,ChallengeMyself,CompetePeers,ChangeWorld,JobSeekingStatus,HoursPerWeek,LastNewJob,AssessJobIndustry,AssessJobRole,AssessJobExp,AssessJobDept,AssessJobTech,AssessJobProjects,AssessJobCompensation,AssessJobOffice,AssessJobCommute,AssessJobRemote,AssessJobLeaders,AssessJobProfDevel,AssessJobDiversity,AssessJobProduct,AssessJobFinances,ImportantBenefits,ClickyKeys,JobProfile,ResumePrompted,LearnedHiring,ImportantHiringAlgorithms,ImportantHiringTechExp,ImportantHiringCommunication,ImportantHiringOpenSource,ImportantHiringPMExp,ImportantHiringCompanies,ImportantHiringTitles,ImportantHiringEducation,ImportantHiringRep,ImportantHiringGettingThingsDone,Currency,Overpaid,TabsSpaces,EducationImportant,EducationTypes,SelfTaughtTypes,TimeAfterBootcamp,CousinEducation,WorkStart,HaveWorkedLanguage,WantWorkLanguage,HaveWorkedFramework,WantWorkFramework,HaveWorkedDatabase,WantWorkDatabase,HaveWorkedPlatform,WantWorkPlatform,IDE,AuditoryEnvironment,Methodology,VersionControl,CheckInCode,ShipIt,OtherPeoplesCode,ProjectManagement,EnjoyDebugging,InTheZone,DifficultCommunication,CollaborateRemote,MetricAssess,EquipmentSatisfiedMonitors,EquipmentSatisfiedCPU,EquipmentSatisfiedRAM,EquipmentSatisfiedStorage,EquipmentSatisfiedRW,InfluenceInternet,InfluenceWorkstation,InfluenceHardware,InfluenceServers,InfluenceTechStack,InfluenceDeptTech,InfluenceVizTools,InfluenceDatabase,InfluenceCloud,InfluenceConsultants,InfluenceRecruitment,InfluenceCommunication,StackOverflowDescribes,StackOverflowSatisfaction,StackOverflowDevices,StackOverflowFoundAnswer,StackOverflowCopiedCode,StackOverflowJobListing,StackOverflowCompanyPage,StackOverflowJobSearch,StackOverflowNewQuestion,StackOverflowAnswer,StackOverflowMetaChat,StackOverflowAdsRelevant,StackOverflowAdsDistracting,StackOverflowModeration,StackOverflowCommunity,StackOverflowHelpful,StackOverflowBetter,StackOverflowWhatDo,StackOverflowMakeMoney,Gender,HighestEducationParents,Race,SurveyLong,QuestionsInteresting,QuestionsConfusing,InterestedAnswers,Salary,ExpectedSalary
587,588,Professional developer,"Yes, I program as a hobby",Egypt,"Yes, full-time","Not employed, but looking for work",Bachelor's degree,Computer science or software engineering,NaN,NaN,NaN,3 to 4 years,Less than a year,NaN,Web developer,Back-end Web developer,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"With a hard ""g,"" like ""gift""",Agree,Agree,Somewhat agree,Strongly agree,Strongly agree,Agree,Strongly agree,Agree,Strongly disagree,Strongly agree,Somewhat agree,Disagree,Somewhat agree,Disagree,Somewhat agree,Disagree,Somewhat agree,I am actively looking for a job,7.0,Not applicable/ never,Not very important,Somewhat important,Somewhat important,Not very important,Important,Somewhat important,Very important,Important,Somewhat important,Not very important,Somewhat important,Important,Important,Somewhat important,Not very important,Annual bonus; Vacation/days off; Health benefi...,No,Hired.com; Indeed; LinkedIn,I was just giving it a regular update,NaN,Important,Important,Very important,Somewhat important,Somewhat important,Not very important,Not very important,Not very important,Somewhat important,Important,NaN,NaN,Tabs,NaN,NaN,NaN,NaN,NaN,9:00 AM,Java; JavaScript; Python,Java; JavaScript; Python,NaN,React,MongoDB; MySQL,Redis,NaN,Android; Amazon Web Services (AWS),Atom; IntelliJ; PyCharm; Visual Studio Code,Turn on some music,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Satisfied,Very satisfied,Somewhat satisfied,Very satisfied,Satisfied,Not at all satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have created a CV or Developer Story on Stac...,8.0,Desktop,Several times,Several times,NaN,Haven't done at all,At least once each week,Several times,Haven't done at all,Haven't done at all,Disagree,Disagree,Somewhat agree,Disagree,Agree,Agree,Agree,Disagree,Male,A bachelor's degree,Middle Eastern,Strongly disagree,Agree,Disagree,Strongly agree,NaN,NaN
1140,1141,Student,"Yes, both",Egypt,"Yes, full-time","Not employed, but looking for work",Bachelor's degree,Computer programming or Web development,NaN,NaN,NaN,2 to 3 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"With a hard ""g,"" like ""gift""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Online course; Part-time/evening course; Self-...,Trade book; Tutoring/mentoring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1367,1368,Student,"Yes, I program as a hobby",Egypt,"Yes, full-time","Not employed, and not looking for work",Some college/university study without earning ...,Computer engineering or electrical/electronics...,NaN,NaN,NaN,3 to 4 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Enunciating each letter: ""gee eye eff""",Strongly agree,Agree,Strongly agree,Disagree,Somewhat agree,Agree,Agree,Agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly disagree,Somewhat agree,Strongly agree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1649,1650,Professional developer,"Yes, I program as a hobby",Egypt,"Yes, full-time","Independent contractor, freelancer, or self-em...",Some college/university study without earning ...,Computer programming or Web development,"Less than half the time, but at least one day ...",NaN,NaN,1 to 2 years,Less than a year,NaN,Web developer; Mobile developer; Data scientis...,NaN,NaN,NaN,10.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Enunciating each letter: ""gee eye eff""",Agree,Agree,Agree,Agree,Agree,Somewhat agree,Strongly agree,Agree,Somewhat agree,Disagree,Disagree,Agree,Disagree,Agree,Agree,Somewhat agree,Strongly agree,"I'm not actively looking, but I am open to new...",21.0,Less than a year ago,Somewhat important,Very important,Very important,Somewhat important,Very important,Somewhat important,Somewhat important,Very important,Important,Very important,Important,Somewhat important,Somewhat important,Somewhat important,Somewhat important,Equipment,Yes,LinkedIn,"I completed a major project, assignment, or co...",NaN,Somewhat important,Very important,Very important,Somewhat important,Somewhat important,Very important,Very important,Very important,Somewhat important,Somewhat important,NaN,NaN,Tabs,NaN,NaN,NaN,NaN,NaN,Noon,Python,Assembly; C; C++; C#; Java; JavaScript,NaN,AngularJS; Hadoop; Node.js; React; Spark; Cord...,NaN,Cassandra; MongoDB; Redis; SQL Server; MySQL; ...,Android; Windows Phone; Windows Desktop; Arduino,Linux Desktop,Atom; Notepad++; Sublime Text; Eclipse; IPytho...,Turn on some music,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not very satisfied,Not very satisfied,Not very satisfied,Not very satisfied,Not very satisfied,Not very satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I've visited Stack Overflow, but haven't logge...",8.0,Desktop; Android browser,Several times,Several times,Haven't done at all,Haven't done at all,Haven't done at all,Haven't done at all,Haven't done at all,Haven't done at all,Somewhat agree,Strongly disagree,Somewhat agree,Somewhat agree,Somewhat agree,Agree,Strongly disagree,Strongly disagree,Male,High school,Middle Eastern,Strongly agree,Agree,Disagree,Strongly agree,NaN,NaN
1850,1851,Professional developer,"Yes, both",Egypt,No,Employed full-time,Bachelor's degree,Computer engineering or electrical/electronics...,A few days each month,"5,000 to 9,999 employees",Publicly-traded corporation,4 to 5 years,Less than a year,NaN,Desktop applications developer,NaN,NaN,NaN,5.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"With a hard ""g,"" like ""gift""",Agree,Strongly agree,Strongly agree,Somewhat agree,Somewhat agree,Strongly agree,Disagree,Agree,Strongly disagree,Strongly agree,Agree,Strongly agree,Agree,Somewhat agree,Strongly agree,Disagree,Somewhat agree,I am actively looking for a job,2.0,Not applicable/ never,Very important,Somewhat important,Not very important,Somewhat important,Somewhat important,Important,Very important,Very important,Important,Important,Very important,Very important,Very important,Very important,Very important,Retirement; Vacation/days off; Health benefits...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spaces,Important,Online course; Self-taught; Coding competition...,Official documentation; Textbook; Stack Overfl...,NaN,NaN,6:00 AM,C; C++; CoffeeScript; JavaScript,Go; Java; JavaScript; Python; Ruby,Node.js; Spark,AngularJS; Hadoop; Node.js; Spark; Firebase,MongoDB,MongoDB,Android; Linux Desktop,Android; Linux Desktop,Sublime Text; Vim; Android Studio,Keep the room absolutely quiet,Waterfall; Agile; Extreme,I use some other system,A few times a month,Somewhat agree,Agree,Somewhat agree,Strongly agree,Agree,Strongly agree,Strongly disagree,On time/in budget,Somewhat satisfied,Very satisfied,Very satisfied,Somewhat satisfied,Very satisfied,Somewhat satisfied,I am the final decision maker,No influence at all,No influence at all,No influence at all,No influence at all,No influence at all,No influence at all,No influence at all,No influence at all,No influence at all,No influence at all,I have created a CV or Developer Story on Stac...,7.0,Desktop; Android app,At least once each week,Once or twice,At least once each day,Haven't done at all,Once or twice,Once or twice,Several times,Haven't done at all,Agree,Disagree,Disagree,Agree,Agree,Strongly agree,Agree,Disagree,Male,A bachelor's degree,Middle Eastern,Strongly agree,Agree,Agree,Strongly agree,NaN,NaN

In [77]:
country_grp['WantWorkLanguage'].value_counts()

Country      WantWorkLanguage
Afghanistan  Assembly; C; C++; C#; F#; Groovy; JavaScript                         1
             PHP; SQL                                                             1
             Java; Ruby                                                           1
             Go                                                                   1
             F#; JavaScript; Lua; Objective-C; PHP; Rust; Swift; VB.NET           1
                                                                                 ..
Zimbabwe     C++; C#; Java; JavaScript; Matlab; PHP; Python; Ruby; SQL; VB.NET    1
             C#; Java; JavaScript                                                 1
             C#; Groovy; Java; JavaScript; SQL                                    1
             Assembly; C++; JavaScript; Python; Ruby                              1
             Java; JavaScript; Objective-C; PHP; SQL                              1
Name: count, Length: 21607, dtype: int64

In [87]:
country_grp['WantWorkLanguage'].value_counts().loc["Egypt"]

WantWorkLanguage
Python                          3
Go; JavaScript; Python          2
Java; JavaScript                2
C++; Python                     2
C; C++                          2
                               ..
Python; R; Scala                1
Objective-C; Python; R; Ruby    1
JavaScript; Python; SQL         1
JavaScript; Python              1
JavaScript; Matlab; PHP         1
Name: count, Length: 68, dtype: int64

In [99]:
country_grp['DeveloperType'].value_counts().loc['Germany']

DeveloperType
Web developer                                                                                                                   579
Desktop applications developer                                                                                                  186
Web developer; Desktop applications developer                                                                                   146
Web developer; Mobile developer                                                                                                 102
Other                                                                                                                            90
                                                                                                                               ...
Web developer; Mobile developer; Graphic designer; Quality assurance engineer                                                     1
Web developer; Mobile developer; Graphic designer; Other                                                                          1
Web developer; Mobile developer; Graphic designer; DevOps specialist                                                              1
Web developer; Mobile developer; Graphic designer; Desktop applications developer; Systems administrator                          1
Web developer; Mobile developer; Embedded applications/devices developer; Machine learning specialist; Systems administrator      1
Name: count, Length: 475, dtype: int64

In [109]:
z = country_grp['DeveloperType'].value_counts().loc['Germany']
z.head(1)

DeveloperType
Web developer    579
Name: count, dtype: int64

0    Web developer
Name: DeveloperType, dtype: object

In [128]:
# getting most common developer type for each country and his percentage

#Note : The idxmax() function in Pandas is used to find the index of the first occurrence of the maximum value in a Series.



def get_most_common_developer(countries):
  data=[]
  for country in countries:
    most_common = (country_grp['DeveloperType'].value_counts(normalize=True).loc[country].idxmax())
    percent = (country_grp['DeveloperType'].value_counts(normalize=True).loc[country]).max() * 100
    data.append((country, most_common, percent))
  return pd.DataFrame(data, columns=['Country', 'Developer Type', 'Percentage'])



get_most_common_developer(['Egypt', 'Germany', 'India', 'United States'])

         Country Developer Type  Percentage
0          Egypt  Web developer   31.460674
1        Germany  Web developer   20.925190
2          India  Web developer   35.194881
3  United States  Web developer   30.428503

In [140]:
def get_most_common_developer_all_countries(country_grp):
    data = []
    for country, group in country_grp:

        dev_type_counts = group['DeveloperType'].value_counts()

        if dev_type_counts.empty:
          continue

        most_common = dev_type_counts.idxmax()

        devs_no = dev_type_counts.max()
        data.append([country, most_common, devs_no])

    return pd.DataFrame(data, columns=['Country', 'Most Common Developer Type', 'No. of Developers']).sort_values(by='No. of Developers', ascending=False)



get_most_common_developer_all_countries(country_grp).head(14)

                Country Most Common Developer Type  No. of Developers
172       United States              Web developer               2528
75                India              Web developer               1210
171      United Kingdom              Web developer               1129
61              Germany              Web developer                579
35               Canada              Web developer                453
57               France              Web developer                337
128              Poland              Web developer                326
150               Spain              Web developer                216
13            Australia              Web developer                200
135  Russian Federation              Web developer                192
113         Netherlands              Web developer                172
134             Romania              Web developer                160
28               Brazil              Web developer                153
81                Italy              Web developer                150